In [1]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/campusx-official/fastapi-demo-api/refs/heads/main/insurance.csv')
data.head(10)

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,67,119.8,1.56,2.920000,False,Jaipur,retired,High
1,36,101.1,1.83,34.280000,False,Chennai,freelancer,Low
2,39,56.8,1.64,36.640000,False,Indore,freelancer,Low
3,22,109.4,1.55,3.340000,True,Mumbai,student,Medium
4,69,62.2,1.60,3.940000,True,Indore,retired,High
5,53,62.9,1.66,50.000000,False,Kota,freelancer,Medium
6,19,80.1,1.68,3.590000,True,Hyderabad,student,Medium
7,31,105.7,1.78,10.865821,True,Delhi,government_job,Medium
8,73,58.0,1.58,1.780000,False,Chandigarh,retired,Medium
9,58,74.4,1.73,43.070000,False,Pune,business_owner,Low

In [7]:
for i in data.index: print(f"Index: {i}, age: {data['age'][i]}, weight: {data['weight'][i]}, height: {data['height'][i]}, income_lpa: {data['income_lpa'][i]}, smoker: {data['smoker'][i]}, city: {data['city'][i]}, occupation: {data['occupation'][i]}, insurance_premium_category: {data['insurance_premium_category'][i]}")

Index: 0, age: 67, weight: 119.8, height: 1.56, income_lpa: 2.92, smoker: False, city: Jaipur, occupation: retired, insurance_premium_category: High
Index: 1, age: 36, weight: 101.1, height: 1.83, income_lpa: 34.28, smoker: False, city: Chennai, occupation: freelancer, insurance_premium_category: Low
Index: 2, age: 39, weight: 56.8, height: 1.64, income_lpa: 36.64, smoker: False, city: Indore, occupation: freelancer, insurance_premium_category: Low
Index: 3, age: 22, weight: 109.4, height: 1.55, income_lpa: 3.34, smoker: True, city: Mumbai, occupation: student, insurance_premium_category: Medium
Index: 4, age: 69, weight: 62.2, height: 1.6, income_lpa: 3.94, smoker: True, city: Indore, occupation: retired, insurance_premium_category: High
Index: 5, age: 53, weight: 62.9, height: 1.66, income_lpa: 50.0, smoker: False, city: Kota, occupation: freelancer, insurance_premium_category: Medium
Index: 6, age: 19, weight: 80.1, height: 1.68, income_lpa: 3.59, smoker: True, city: Hyderabad, occupation: student, insurance_premium_category: Medium
Index: 7, age: 31, weight: 105.7, height: 1.78, income_lpa: 10.865820771380372, smoker: True, city: Delhi, occupation: government_job, insurance_premium_category: Medium
Index: 8, age: 73, weight: 58.0, height: 1.58, income_lpa: 1.78, smoker: False, city: Chandigarh, occupation: retired, insurance_premium_category: Medium
Index: 9, age: 58, weight: 74.4, height: 1.73, income_lpa: 43.07, smoker: False, city: Pune, occupation: business_owner, insurance_premium_category: Low
Index: 10, age: 29, weight: 71.9, height: 1.77, income_lpa: 32.78, smoker: True, city: Chennai, occupation: business_owner, insurance_premium_category: Medium
Index: 11, age: 25, weight: 77.2, height: 1.56, income_lpa: 10.899386596696989, smoker: True, city: Pune, occupation: government_job, insurance_premium_category: Low
Index: 12, age: 42, weight: 95.2, height: 1.78, income_lpa: 17.58, smoker: True, city: Chandigarh, occupation: freelancer, insurance_premium_category: High
Index: 13, age: 28, weight: 93.4, height: 1.84, income_lpa: 11.95, smoker: False, city: Kolkata, occupation: freelancer, insurance_premium_category: Low
Index: 14, age: 49, weight: 89.3, height: 1.65, income_lpa: 13.50516648107039, smoker: False, city: Kota, occupation: government_job, insurance_premium_category: Medium
Index: 15, age: 61, weight: 61.7, height: 1.68, income_lpa: 2.99, smoker: True, city: Delhi, occupation: retired, insurance_premium_category: Medium
Index: 16, age: 66, weight: 70.2, height: 1.59, income_lpa: 0.61, smoker: False, city: Pune, occupation: retired, insurance_premium_category: Medium
Index: 17, age: 65, weight: 90.1, height: 1.7, income_lpa: 2.23, smoker: False, city: Delhi, occupation: retired, insurance_premium_category: Medium
Index: 18, age: 52, weight: 80.9, height: 1.8, income_lpa: 38.14, smoker: True, city: Kota, occupation: business_owner, insurance_premium_category: High
Index: 19, age: 24, weight: 111.2, height: 1.6, income_lpa: 2.79, smoker: True, city: Lucknow, occupation: student, insurance_premium_category: High
Index: 20, age: 34, weight: 58.2, height: 1.85, income_lpa: 30.65, smoker: True, city: Gaya, occupation: business_owner, insurance_premium_category: Medium
Index: 21, age: 69, weight: 92.7, height: 1.84, income_lpa: 2.91, smoker: False, city: Jalandhar, occupation: retired, insurance_premium_category: High
Index: 22, age: 57, weight: 106.4, height: 1.83, income_lpa: 30.0, smoker: False, city: Chandigarh, occupation: government_job, insurance_premium_category: Low
Index: 23, age: 35, weight: 70.3, height: 1.78, income_lpa: 23.71, smoker: False, city: Mysore, occupation: unemployed, insurance_premium_category: Medium
Index: 24, age: 50, weight: 54.2, height: 1.66, income_lpa: 18.6, smoker: False, city: Mysore, occupation: private_job, insurance_premium_category: Medium
Index: 25, age: 59, weight: 60.2, height: 1.55, income_lpa: 30.0, smoker: False, city: Mysore, occupation: government_job, insurance_premium_category: Low
Index: 26, age: 33, weight: 79.0, height: 1.61, income_lpa: 23.61, smoker: False, city: Jaipur, occupation: freelancer, insurance_premium_category: Medium
Index: 27, age: 58, weight: 111.4, height: 1.78, income_lpa: 34.33, smoker: False, city: Lucknow, occupation: private_job, insurance_premium_category: Medium
Index: 28, age: 38, weight: 101.2, height: 1.79, income_lpa: 11.63, smoker: False, city: Mumbai, occupation: unemployed, insurance_premium_category: Low
Index: 29, age: 60, weight: 117.8, height: 1.66, income_lpa: 50.0, smoker: True, city: Lucknow, occupation: business_owner, insurance_premium_category: High
Index: 30, age: 35, weight: 89.6, height: 1.73, income_lpa: 32.97, smoker: False, city: Delhi, occupation: business_owner, insurance_premium_category: Low
Index: 31, age: 39, weight: 51.1, height: 1.83, income_lpa: 11.77, smoker: True, city: Lucknow, occupation: private_job, insurance_premium_category: Medium
Index: 32, age: 47, weight: 113.7, height: 1.9, income_lpa: 50.0, smoker: False, city: Jalandhar, occupation: private_job, insurance_premium_category: Medium
Index: 33, age: 73, weight: 67.5, height: 1.76, income_lpa: 1.46, smoker: False, city: Mumbai, occupation: retired, insurance_premium_category: Medium
Index: 34, age: 75, weight: 100.8, height: 1.75, income_lpa: 0.68, smoker: True, city: Kota, occupation: retired, insurance_premium_category: High
Index: 35, age: 59, weight: 59.3, height: 1.69, income_lpa: 43.28, smoker: True, city: Chandigarh, occupation: private_job, insurance_premium_category: Medium
Index: 36, age: 61, weight: 58.4, height: 1.64, income_lpa: 0.53, smoker: False, city: Hyderabad, occupation: retired, insurance_premium_category: Medium
Index: 37, age: 26, weight: 57.2, height: 1.79, income_lpa: 8.09, smoker: False, city: Indore, occupation: freelancer, insurance_premium_category: Medium
Index: 38, age: 74, weight: 111.2, height: 1.83, income_lpa: 1.84, smoker: True, city: Jaipur, occupation: retired, insurance_premium_category: High
Index: 39, age: 51, weight: 100.6, height: 1.68, income_lpa: 11.99, smoker: True, city: Bangalore, occupation: unemployed, insurance_premium_category: High
Index: 40, age: 44, weight: 57.0, height: 1.53, income_lpa: 40.19, smoker: True, city: Pune, occupation: unemployed, insurance_premium_category: Medium
Index: 41, age: 64, weight: 59.8, height: 1.63, income_lpa: 3.87, smoker: False, city: Mumbai, occupation: retired, insurance_premium_category: Medium
Index: 42, age: 23, weight: 69.9, height: 1.79, income_lpa: 2.6, smoker: True, city: Mysore, occupation: student, insurance_premium_category: Medium
Index: 43, age: 72, weight: 85.7, height: 1.71, income_lpa: 1.56, smoker: False, city: Chennai, occupation: retired, insurance_premium_category: Medium
Index: 44, age: 59, weight: 77.0, height: 1.6, income_lpa: 50.0, smoker: True, city: Lucknow, occupation: private_job, insurance_premium_category: Medium
Index: 45, age: 58, weight: 75.3, height: 1.5, income_lpa: 18.39, smoker: False, city: Jalandhar, occupation: unemployed, insurance_premium_category: High
Index: 46, age: 42, weight: 83.0, height: 1.57, income_lpa: 25.57, smoker: True, city: Kolkata, occupation: unemployed, insurance_premium_category: High
Index: 47, age: 55, weight: 116.4, height: 1.87, income_lpa: 8.34, smoker: False, city: Chandigarh, occupation: private_job, insurance_premium_category: Medium
Index: 48, age: 36, weight: 94.8, height: 1.66, income_lpa: 32.69, smoker: True, city: Chennai, occupation: unemployed, insurance_premium_category: Medium
Index: 49, age: 23, weight: 106.6, height: 1.58, income_lpa: 2.29, smoker: False, city: Kota, occupation: student, insurance_premium_category: Medium
Index: 50, age: 55, weight: 66.7, height: 1.88, income_lpa: 25.23, smoker: True, city: Jaipur, occupation: private_job, insurance_premium_category: Medium
Index: 51, age: 45, weight: 101.9, height: 1.62, income_lpa: 28.95, smoker: True, city: Jaipur, occupation: private_job, insurance_premium_category: High
Index: 52, age: 18, weight: 116.7, height: 1.57, income_lpa: 2.96, smoker: False, city: Jalandhar, occupation: student, insurance_premium_category: Medium
Index: 53, age: 41, weight: 101.3, height: 1.85, income_lpa: 30.0, smoker: True, city: Delhi, occupation: government_job, insurance_premium_category: Medium
Index: 54, age: 75, weight: 54.5, height: 1.61, income_lpa: 3.32, smoker: True, city: Lucknow, occupation: retired, insurance_premium_category: High
Index: 55, age: 47, weight: 75.7, height: 1.73, income_lpa: 24.93, smoker: False, city: Delhi, occupation: unemployed, insurance_premium_category: Low
Index: 56, age: 24, weight: 101.9, height: 1.55, income_lpa: 2.86, smoker: True, city: Kolkata, occupation: student, insurance_premium_category: Medium
Index: 57, age: 72, weight: 76.8, height: 1.69, income_lpa: 1.36, smoker: True, city: Jalandhar, occupation: retired, insurance_premium_category: High
Index: 58, age: 72, weight: 95.9, height: 1.79, income_lpa: 3.31, smoker: True, city: Indore, occupation: retired, insurance_premium_category: High
Index: 59, age: 61, weight: 118.7, height: 1.82, income_lpa: 1.13, smoker: False, city: Jaipur, occupation: retired, insurance_premium_category: High
Index: 60, age: 41, weight: 101.3, height: 1.81, income_lpa: 49.94, smoker: True, city: Jalandhar, occupation: unemployed, insurance_premium_category: High
Index: 61, age: 32, weight: 102.4, height: 1.68, income_lpa: 24.05, smoker: True, city: Chandigarh, occupation: unemployed, insurance_premium_category: High
Index: 62, age: 34, weight: 72.8, height: 1.83, income_lpa: 35.67, smoker: False, city: Chennai, occupation: business_owner, insurance_premium_category: Low
Index: 63, age: 47, weight: 71.3, height: 1.82, income_lpa: 41.66, smoker: True, city: Gaya, occupation: business_owner, insurance_premium_category: High
Index: 64, age: 71, weight: 117.8, height: 1.78, income_lpa: 1.02, smoker: False, city: Chandigarh, occupation: retired, insurance_premium_category: High
Index: 65, age: 46, weight: 106.3, height: 1.68, income_lpa: 38.07, smoker: True, city: Jaipur, occupation: unemployed, insurance_premium_category: High
Index: 66, age: 18, weight: 63.9, height: 1.59, income_lpa: 3.23, smoker: False, city: Indore, occupation: student, insurance_premium_category: Low
Index: 67, age: 22, weight: 56.4, height: 1.82, income_lpa: 2.76, smoker: False, city: Jaipur, occupation: student, insurance_premium_category: Low
Index: 68, age: 20, weight: 80.3, height: 1.87, income_lpa: 0.68, smoker: False, city: Lucknow, occupation: student, insurance_premium_category: Low
Index: 69, age: 46, weight: 67.2, height: 1.75, income_lpa: 6.034486970484345, smoker: False, city: Lucknow, occupation: government_job, insurance_premium_category: Low
Index: 70, age: 69, weight: 99.9, height: 1.65, income_lpa: 0.57, smoker: False, city: Chandigarh, occupation: retired, insurance_premium_category: High
Index: 71, age: 38, weight: 54.1, height: 1.81, income_lpa: 20.25, smoker: False, city: Chandigarh, occupation: unemployed, insurance_premium_category: Low
Index: 72, age: 70, weight: 116.3, height: 1.81, income_lpa: 3.08, smoker: False, city: Indore, occupation: retired, insurance_premium_category: High
Index: 73, age: 69, weight: 84.3, height: 1.62, income_lpa: 2.22, smoker: True, city: Kolkata, occupation: retired, insurance_premium_category: High
Index: 74, age: 63, weight: 71.1, height: 1.54, income_lpa: 1.88, smoker: True, city: Jalandhar, occupation: retired, insurance_premium_category: High
Index: 75, age: 53, weight: 62.3, height: 1.74, income_lpa: 45.07, smoker: False, city: Hyderabad, occupation: unemployed, insurance_premium_category: Low
Index: 76, age: 62, weight: 99.1, height: 1.5, income_lpa: 1.12, smoker: False, city: Mysore, occupation: retired, insurance_premium_category: High
Index: 77, age: 67, weight: 114.5, height: 1.74, income_lpa: 0.61, smoker: True, city: Mumbai, occupation: retired, insurance_premium_category: High
Index: 78, age: 52, weight: 95.6, height: 1.85, income_lpa: 14.74, smoker: True, city: Jalandhar, occupation: freelancer, insurance_premium_category: High
Index: 79, age: 39, weight: 55.3, height: 1.56, income_lpa: 30.0, smoker: True, city: Indore, occupation: government_job, insurance_premium_category: Low
Index: 80, age: 56, weight: 95.8, height: 1.67, income_lpa: 50.0, smoker: False, city: Jalandhar, occupation: unemployed, insurance_premium_category: High
Index: 81, age: 41, weight: 82.6, height: 1.61, income_lpa: 22.19, smoker: True, city: Mysore, occupation: freelancer, insurance_premium_category: High
Index: 82, age: 35, weight: 56.0, height: 1.77, income_lpa: 12.96, smoker: False, city: Delhi, occupation: unemployed, insurance_premium_category: Low
Index: 83, age: 61, weight: 83.3, height: 1.85, income_lpa: 2.16, smoker: True, city: Kota, occupation: retired, insurance_premium_category: High
Index: 84, age: 75, weight: 86.2, height: 1.73, income_lpa: 0.62, smoker: True, city: Jaipur, occupation: retired, insurance_premium_category: High
Index: 85, age: 33, weight: 51.4, height: 1.86, income_lpa: 34.66, smoker: False, city: Chennai, occupation: private_job, insurance_premium_category: Low
Index: 86, age: 35, weight: 66.0, height: 1.89, income_lpa: 37.38, smoker: False, city: Hyderabad, occupation: freelancer, insurance_premium_category: Low
Index: 87, age: 30, weight: 82.0, height: 1.6, income_lpa: 25.59837029543476, smoker: False, city: Hyderabad, occupation: government_job, insurance_premium_category: Low
Index: 88, age: 54, weight: 97.4, height: 1.76, income_lpa: 30.0, smoker: False, city: Mumbai, occupation: government_job, insurance_premium_category: Low
Index: 89, age: 24, weight: 108.8, height: 1.89, income_lpa: 4.0, smoker: False, city: Chennai, occupation: student, insurance_premium_category: Low
Index: 90, age: 59, weight: 54.0, height: 1.6, income_lpa: 21.07, smoker: False, city: Mumbai, occupation: business_owner, insurance_premium_category: Low
Index: 91, age: 38, weight: 119.8, height: 1.76, income_lpa: 28.46788535766728, smoker: False, city: Bangalore, occupation: government_job, insurance_premium_category: Low
Index: 92, age: 37, weight: 62.7, height: 1.85, income_lpa: 30.0, smoker: True, city: Lucknow, occupation: government_job, insurance_premium_category: Low
Index: 93, age: 23, weight: 79.4, height: 1.85, income_lpa: 1.28, smoker: False, city: Indore, occupation: student, insurance_premium_category: Low
Index: 94, age: 50, weight: 105.4, height: 1.78, income_lpa: 10.542289178793244, smoker: False, city: Bangalore, occupation: government_job, insurance_premium_category: Low
Index: 95, age: 36, weight: 52.8, height: 1.57, income_lpa: 19.64, smoker: False, city: Indore, occupation: business_owner, insurance_premium_category: Low
Index: 96, age: 26, weight: 113.8, height: 1.54, income_lpa: 34.01, smoker: False, city: Delhi, occupation: private_job, insurance_premium_category: Low
Index: 97, age: 52, weight: 60.8, height: 1.8, income_lpa: 44.86, smoker: False, city: Hyderabad, occupation: freelancer, insurance_premium_category: Low
Index: 98, age: 27, weight: 101.1, height: 1.82, income_lpa: 28.3, smoker: False, city: Kolkata, occupation: business_owner, insurance_premium_category: Low
Index: 99, age: 40, weight: 70.0, height: 1.59, income_lpa: 28.16664036808183, smoker: True, city: Bangalore, occupation: government_job, insurance_premium_category: Low

In [ ]:
# Feature Engineering: Creating a new feature 'bmi' (Body Mass Index) based on weight and height

df = data.copy()

bmi = lambda x: round(x['weight'] / (x['height']) ** 2, 2)

df['bmi'] = df.apply(bmi, axis=1)

In [14]:
# Feature Engineering: Creating a new feature 'age_group' based on age

age_group = lambda x: 'young' if x['age'] < 25 else ('adult' if 25 < x['age'] < 45 else ('middle-aged' if 45 < x['age'] < 60 else 'senior'))

df['age_group'] = df.apply(age_group, axis=1)

In [17]:
# Feature Engineering: Creating a new feature 'age_group' based on age

lifestyle_risk = lambda x: 'high' if x['smoker'] and x['bmi']  > 30 else ('medium' if x['smoker'] and x['bmi'] > 27 else 'low')

df['lifestyle_risk'] = df.apply(lifestyle_risk, axis=1)

In [18]:
# Feature Engineering: Creating a new feature 'city_tier' based on city names

tier_1_cities = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune"]
tier_2_cities = [
    "Jaipur", "Chandigarh", "Indore", "Lucknow", "Patna", "Ranchi", "Visakhapatnam", "Coimbatore",
    "Bhopal", "Nagpur", "Vadodara", "Surat", "Rajkot", "Jodhpur", "Raipur", "Amritsar", "Varanasi",
    "Agra", "Dehradun", "Mysore", "Jabalpur", "Guwahati", "Thiruvananthapuram", "Ludhiana", "Nashik",
    "Allahabad", "Udaipur", "Aurangabad", "Hubli", "Belgaum", "Salem", "Vijayawada", "Tiruchirappalli",
    "Bhavnagar", "Gwalior", "Dhanbad", "Bareilly", "Aligarh", "Gaya", "Kozhikode", "Warangal",
    "Kolhapur", "Bilaspur", "Jalandhar", "Noida", "Guntur", "Asansol", "Siliguri"
]
     
def city_tier(city:str)->int:
    if city in tier_1_cities:
        return 1
    elif city in tier_2_cities:
        return 2
    else:
        return 3

df["city_tier"] = df["city"].apply(city_tier)

In [19]:
df.head(10)

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,bmi,age_group,lifestyle_risk,city_tier
0,67,119.8,1.56,2.920000,False,Jaipur,retired,High,49.23,senior,low,2
1,36,101.1,1.83,34.280000,False,Chennai,freelancer,Low,30.19,adult,low,1
2,39,56.8,1.64,36.640000,False,Indore,freelancer,Low,21.12,adult,low,2
3,22,109.4,1.55,3.340000,True,Mumbai,student,Medium,45.54,young,high,1
4,69,62.2,1.60,3.940000,True,Indore,retired,High,24.30,senior,low,2
5,53,62.9,1.66,50.000000,False,Kota,freelancer,Medium,22.83,middle-aged,low,3
6,19,80.1,1.68,3.590000,True,Hyderabad,student,Medium,28.38,young,medium,1
7,31,105.7,1.78,10.865821,True,Delhi,government_job,Medium,33.36,adult,high,1
8,73,58.0,1.58,1.780000,False,Chandigarh,retired,Medium,23.23,senior,low,2
9,58,74.4,1.73,43.070000,False,Pune,business_owner,Low,24.86,middle-aged,low,1

In [20]:
df.shape

(100, 12)

In [43]:
df.describe()

              age      weight      height  income_lpa         bmi   city_tier
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000
mean    47.180000   83.894000    1.713200   18.400600   28.844600    1.650000
std     16.649312   21.020278    0.110205   16.067465    7.887091    0.592461
min     18.000000   51.100000    1.500000    0.530000   14.860000    1.000000
25%     34.750000   63.650000    1.610000    2.897500   22.127500    1.000000
50%     47.000000   82.300000    1.730000   14.122583   29.455000    2.000000
75%     61.000000  101.300000    1.810000   30.162500   33.307500    2.000000
max     75.000000  119.800000    1.900000   50.000000   49.230000    3.000000

In [46]:
cols = [c for c in df.columns if df[c].dtype == 'object']

for col in cols:
    print(f"Column: {col}, Unique Values: {df[col].unique()}, Unique count: ({df[col].nunique()})")

Column: city, Unique Values: ['Jaipur' 'Chennai' 'Indore' 'Mumbai' 'Kota' 'Hyderabad' 'Delhi'
 'Chandigarh' 'Pune' 'Kolkata' 'Lucknow' 'Gaya' 'Jalandhar' 'Mysore'
 'Bangalore'], Unique count: (15)
Column: occupation, Unique Values: ['retired' 'freelancer' 'student' 'government_job' 'business_owner'
 'unemployed' 'private_job'], Unique count: (7)
Column: insurance_premium_category, Unique Values: ['High' 'Low' 'Medium'], Unique count: (3)
Column: age_group, Unique Values: ['senior' 'adult' 'young' 'middle-aged'], Unique count: (4)
Column: lifestyle_risk, Unique Values: ['low' 'high' 'medium'], Unique count: (3)

In [21]:
df.drop(columns=['age', 'weight', 'height', 'smoker', 'city'])[['income_lpa', 'occupation', 'bmi', 'age_group', 'lifestyle_risk', 'city_tier', 'insurance_premium_category']].sample(5)

,income_lpa,occupation,bmi,age_group,lifestyle_risk,city_tier,insurance_premium_category
91,28.467885,government_job,38.68,adult,low,1,Low
20,30.650000,business_owner,17.01,adult,low,2,Medium
77,0.610000,retired,37.82,senior,high,1,High
35,43.280000,private_job,20.76,middle-aged,low,2,Medium
93,1.280000,student,23.20,young,low,2,Low

In [23]:
X = df[['income_lpa', 'occupation', 'bmi', 'age_group', 'lifestyle_risk', 'city_tier']]
y = df['insurance_premium_category']

In [47]:
X.head(10)

   income_lpa      occupation    bmi    age_group lifestyle_risk  city_tier
0    2.920000         retired  49.23       senior            low          2
1   34.280000      freelancer  30.19        adult            low          1
2   36.640000      freelancer  21.12        adult            low          2
3    3.340000         student  45.54        young           high          1
4    3.940000         retired  24.30       senior            low          2
5   50.000000      freelancer  22.83  middle-aged            low          3
6    3.590000         student  28.38        young         medium          1
7   10.865821  government_job  33.36        adult           high          1
8    1.780000         retired  23.23       senior            low          2
9   43.070000  business_owner  24.86  middle-aged            low          1

In [25]:
X.shape, y.shape

((100, 6), (100,))

In [26]:
X.isnull().sum(), y.isnull().sum()

(income_lpa        0
 occupation        0
 bmi               0
 age_group         0
 lifestyle_risk    0
 city_tier         0
 dtype: int64,
 np.int64(0))

In [29]:
X.duplicated().sum()

np.int64(0)

In [ ]:
# Define categorical and numeric features
categorical_features = ["age_group", "lifestyle_risk", "occupation", "city_tier"]
numeric_features = ["bmi", "income_lpa"]

In [30]:
# Define categorical and numeric features
categorical_features = ["age_group", "lifestyle_risk", "occupation", "city_tier"]
numeric_features = ["bmi", "income_lpa"]

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Create column transformer for OHE
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(), categorical_features),
        ("num", "passthrough", numeric_features)
    ]
)

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

# Create a pipeline with preprocessing and random forest classifier
pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=42))
])

In [34]:
from sklearn.model_selection import train_test_split

# Split data and train model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  ['age_group',
                                                   'lifestyle_risk',
                                                   'occupation', 'city_tier']),
                                                 ('num', 'passthrough',
                                                  ['bmi', 'income_lpa'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [37]:
from sklearn.metrics import classification_report, accuracy_score

y_pred = pipeline.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred)*100,'%')
print("Classification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 80.0 %
Classification Report:
              precision    recall  f1-score   support

        High       0.86      0.86      0.86         7
         Low       0.67      1.00      0.80         4
      Medium       0.86      0.67      0.75         9

    accuracy                           0.80        20
   macro avg       0.79      0.84      0.80        20
weighted avg       0.82      0.80      0.80        20

In [42]:
for i in range(len(y_test)):
    print(f"Index: {i}, Actual: {y_test.iloc[i]}, Predicted: {y_pred[i]}")
    print("Correct Prediction" if y_test.iloc[i] == y_pred[i] else "Incorrect Prediction")

Index: 0, Actual: High, Predicted: High
Correct Prediction
Index: 1, Actual: High, Predicted: High
Correct Prediction
Index: 2, Actual: Medium, Predicted: Medium
Correct Prediction
Index: 3, Actual: High, Predicted: High
Correct Prediction
Index: 4, Actual: Low, Predicted: Low
Correct Prediction
Index: 5, Actual: Medium, Predicted: Medium
Correct Prediction
Index: 6, Actual: Medium, Predicted: Medium
Correct Prediction
Index: 7, Actual: Low, Predicted: Low
Correct Prediction
Index: 8, Actual: Low, Predicted: Low
Correct Prediction
Index: 9, Actual: High, Predicted: High
Correct Prediction
Index: 10, Actual: Low, Predicted: Low
Correct Prediction
Index: 11, Actual: High, Predicted: High
Correct Prediction
Index: 12, Actual: Medium, Predicted: Medium
Correct Prediction
Index: 13, Actual: Medium, Predicted: Low
Incorrect Prediction
Index: 14, Actual: High, Predicted: High
Correct Prediction
Index: 15, Actual: Medium, Predicted: Medium
Correct Prediction
Index: 16, Actual: Medium, Predicted: Medium
Correct Prediction
Index: 17, Actual: Medium, Predicted: High
Incorrect Prediction
Index: 18, Actual: High, Predicted: Medium
Incorrect Prediction
Index: 19, Actual: Medium, Predicted: Low
Incorrect Prediction

In [38]:
import pickle

model_path = "insurance_premium_model.pkl"

with open(model_path, "wb") as f:
    pickle.dump(pipeline, f)